/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'latitude' : number,
  'deliveryCharge' : number,
  'total' : number,
  'customerPhone' : string,
  'distanceKm' : number,
  'longitude' : number,
  'village' : string,
  'timestamp' : bigint,
  'customerId' : string,
  'items' : Array<OrderItem>,
  'subtotal' : number,
}
export interface OrderItem {
  'unit' : string,
  'productId' : bigint,
  'productName' : string,
  'quantity' : number,
  'price' : number,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'unit' : string,
  'available' : boolean,
  'imageUrl' : string,
  'category' : string,
  'price' : number,
}
export interface UserProfile {
  'name' : string,
  'village' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[string, string, number, string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOrder' : ActorMethod<[bigint], Order>,
  'getOrdersByCustomer' : ActorMethod<[string], Array<Order>>,
  'getProduct' : ActorMethod<[bigint], Product>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAdmin' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markDelivered' : ActorMethod<[bigint], undefined>,
  'placeOrder' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      Array<OrderItem>,
      number,
      number,
      number,
      number,
      number,
      number,
    ],
    bigint
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateProduct' : ActorMethod<
    [bigint, string, string, number, string, string, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];